### ISSUE TITLE
Error message when writing FDS file...

### ISSUE THREAD

**Issue by Mikkelmhfire** [firemodels/fds#13820]
**Describe the bug**
Whenever i try to write fds file i get the following error message. My java is updated to the latest version and i never ran into this error message before.

I have also tried to open and write fds files from some old models that have worked perfectly, and here i get the same error message... The error accourd after the new update in Pyrosim.

ERROR MESSAGE BELOW:

PyroSim Version: 2024.2.1120 x64
Date: November 30, 2024, 11:47:02 AM CET
Operating System: Windows 11 (amd64)
Java Version: 21.0.2

java.lang.NullPointerException: Cannot invoke "pyrosim.io.fds.FDSRenderRecord.setValue(String, Object)" because "rec" is null
	at pyrosim.io.fds.v6.renderers.ControlRenderer.renderIntCompareOp(ControlRenderer.java:469)
	at pyrosim.io.fds.v6.renderers.ControlRenderer.renderIntGreaterThanOp(ControlRenderer.java:448)
	at pyrosim.io.fds.v6.renderers.ControlRenderer.render(ControlRenderer.java:150)
	at pyrosim.io.fds.v6.renderers.ControlRenderer.render(ControlRenderer.java:128)
	at pyrosim.io.fds.v6.renderers.AFDS6Renderer.render(AFDS6Renderer.java:95)
	at pyrosim.io.fds.v6.renderers.FDS6Renderer.renderRecords(FDS6Renderer.java:366)
	at pyrosim.io.fds.v6.renderers.FDS6Renderer.renderObjects(FDS6Renderer.java:339)
	at pyrosim.io.fds.v6.renderers.FDS6Renderer.renderFileForVersion(FDS6Renderer.java:169)
	at pyrosim.io.fds.v6.renderers.FDS6Renderer.renderFileForVersion(FDS6Renderer.java:231)
	at pyrosim.io.fds.FDSRenderer.renderFile(FDSRenderer.java:282)
	at pyrosim.io.fds.FDSRenderer.renderFile(FDSRenderer.java:262)
	at pyrosim.PyroSim.writeFDSFile(PyroSim.java:2360)
	at pyrosim.PyroSim$ExportFDSFileAction.actionPerformed(PyroSim.java:2573)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Desktop (please complete the following information):**
 - windows 11 home 64 bit

**Comment by drjfloyd** [comment]
Contact Thunderhead Engineering for issues with their product.
