### ISSUE TITLE
ht3d: possible bug

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#6128]
Randy,
I was working on some cases reported by James in discussion group [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/fds-smv/mSKwT1zWkOg/6YA7BtZMAAAJ)
Run this case with bundle failed. Here is some debugging from the up to date code: 

```
 Fire Dynamics Simulator

 Current Date     : March  8, 2018  00:17:48
 Revision         : FDS6.6.0-1325-g238fe5a-master
 Revision Date    : Wed Mar 7 16:06:27 2018 -0500
 Compiler         : Intel ifort 17.0.3
 Compilation Date : Mar 08, 2018  00:16:41

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Enabled; Number of OpenMP Threads:      1

 MPI version: 3.1
 MPI library version: Open MPI v3.0.0, package: Open MPI salah@benkorichi Distribution, ident: 3.0.0, repo rev: v3.0.0, Sep 12, 2017

 Job TITLE        : Heat conduction example
 Job ID string    : 660_NETHF-52_w_HT3D

forrtl: severe (408): fort: (3): Subscript #1 of the array MU_RSQMW_Z has value -94 which is less than the lower bound of 0

Image              PC                Routine            Line        Source             
fds_mpi_intel_lin  000000000902F7D6  Unknown               Unknown  Unknown
fds_mpi_intel_lin  000000000059C5BF  physical_function        2621  func.f90
fds_mpi_intel_lin  0000000002F12033  wall_routines_mp_        2832  wall.f90
fds_mpi_intel_lin  0000000002DE2FA7  wall_routinesther         328  wall.f90
fds_mpi_intel_lin  0000000002DD02DD  wall_routines_mp_         138  wall.f90
fds_mpi_intel_lin  0000000002DCB448  wall_routines_mp_          48  wall.f90
fds_mpi_intel_lin  00000000035FBA14  MAIN__                    685  main.f90
fds_mpi_intel_lin  000000000040CDAE  Unknown               Unknown  Unknown
libc-2.23.so       000014FC300B8830  __libc_start_main     Unknown  Unknown
fds_mpi_intel_lin  000000000040CCA9  Unknown               Unknown  Unknown
```
[660_NETHF-52_w_HT3D.fds.txt](https://github.com/firemodels/fds/files/1791378/660_NETHF-52_w_HT3D.fds.txt)

I was trying to simplify the case for the user, and then I noticed this issue when NET_HEAT_FLUX approaches -20. -10 to positive values are okay.

**Comment by sbenkorichi** [comment]
I wonder what's causing it to get out of bounds
```
At line 2621 of file ../../Source/func.f90
Fortran runtime error: Index '-94' of dimension 1 of array 'mu_rsqmw_z' outside of expected range (0:5000)

Error termination. Backtrace:
#0  0x153bc7504fba in ???
#1  0x153bc7505ba5 in ???
#2  0x153bc7505f77 in ???
#3  0x4ae7c2 in __physical_functions_MOD_get_viscosity
	at ../../Source/func.f90:2621
#4  0x123dc1c in heat_transfer_coefficient
	at ../../Source/wall.f90:2832
#5  0x128f1bb in calculate_tmp_f
	at ../../Source/wall.f90:328
#6  0x1268e25 in thermal_bc
	at ../../Source/wall.f90:138
#7  0x129de37 in __wall_routines_MOD_wall_bc
	at ../../Source/wall.f90:48
#8  0x14b040f in fds
	at ../../Source/main.f90:685
#9  0x15320e2 in main
	at ../../Source/main.f90:5

```

**Comment by rmcdermo** [comment]
Case runs fine with latest source.

**Comment by sbenkorichi** [comment]
that's weird really,
Why it failed on both intel 17 and gnu on my end. 
I've updated my repo before I compiled the code, but it didn't run. On the bundle, you would receive access violation immediately, but with the latest source, I received the above errors.

I can't understand why it's not working. The issues appears when I start reducing the NET_HEAT_FLUX values.

**Comment by rmcdermo** [comment]
I am running with _dv version.  You?

**Comment by sbenkorichi** [comment]
aha I'm with _db 
for both compilers. 
I will try _dv though later

**Comment by rmcdermo** [comment]
OK, I see the error in _db.

**Comment by rmcdermo** [comment]
Don't use SOLID_PHASE_ONLY=T.

**Comment by sbenkorichi** [comment]
Any reason for that?

**Comment by rmcdermo** [comment]
By setting NET_HEAT_FLUX, you are asking FDS to do a convective heat transfer calculation, which is *not* a solid phase calculation.

**Comment by sbenkorichi** [comment]
Oh my,
my bad, didn't watch out for that trap in the middle of the night lol

Thanks though !

**Comment by rmcdermo** [comment]
Actually, I found a simple fix for this.  But I am also doing other surgery in wall.f90 that I am not ready to push up.  So, once I push the other stuff up, it will work with SOLID_PHASE_ONLY.  It will just compute a heat transfer coefficient like DNS (low Reynolds number).

**Comment by sbenkorichi** [comment]
Nice,
I will review it when you push it.
Please get back to this ticket when you do push the specific commit so I can look at it as well.

Thanks !

**Comment by rmcdermo** [comment]
Should work with PR #6131

**Comment by sbenkorichi** [comment]
Thanks,
I will compile and report later.

**Comment by sbenkorichi** [comment]
before the commit,
I confirm the dv helps, but when I commented the solid phase only, but it still gives an error with gnu db. 

```
 Time Step:      1, Simulation Time:    0.0004 s
 Time Step:      2, Simulation Time:    0.0008 s
 Time Step:      3, Simulation Time:     0.001 s
 Time Step:      4, Simulation Time:     0.002 s
 Time Step:      5, Simulation Time:     0.002 s
 Time Step:      6, Simulation Time:     0.003 s
 Time Step:      7, Simulation Time:     0.004 s
 Time Step:      8, Simulation Time:     0.005 s
 Time Step:      9, Simulation Time:     0.005 s
 Time Step:     10, Simulation Time:     0.006 s
 Time Step:     20, Simulation Time:      0.02 s
 Time Step:     30, Simulation Time:      0.06 s
At line 2410 of file ../../Source/func.f90
Fortran runtime error: Index '-4' of dimension 1 of array 'h_sens_z' outside of expected range (0:5000)

Error termination. Backtrace:
#0  0x15015f1fefba in ???
#1  0x15015f1ffba5 in ???
#2  0x15015f1fff77 in ???
#3  0x4b0d93 in __physical_functions_MOD_get_sensible_enthalpy
	at ../../Source/func.f90:2410
#4  0x130b2c5 in enthalpy_advection
	at ../../Source/divg.f90:917
#5  0x12fae08 in __divg_MOD_divergence_part_1
	at ../../Source/divg.f90:586
#6  0x14b0808 in fds
	at ../../Source/main.f90:711
#7  0x1532082 in main
	at ../../Source/main.f90:5
```
after the commit,
it's fixed.
With solid phase only, it works.

Thanks !

**Comment by sbenkorichi** [comment]
As for case 2. 
with intel dv 
```
 Time Step:      1, Simulation Time:      0.01 s
 Time Step:      2, Simulation Time:      0.02 s
 Time Step:      3, Simulation Time:      0.03 s
 Time Step:      4, Simulation Time:      0.04 s
 Time Step:      5, Simulation Time:      0.05 s
 Time Step:      6, Simulation Time:      0.06 s
 Time Step:      7, Simulation Time:      0.08 s
 Time Step:      8, Simulation Time:      0.09 s
 Time Step:      9, Simulation Time:      0.10 s
 Time Step:     10, Simulation Time:      0.11 s
 Time Step:     20, Simulation Time:      0.16 s
 Time Step:     30, Simulation Time:      0.17 s
 Time Step:     40, Simulation Time:      0.17 s
 Time Step:     50, Simulation Time:      0.17 s
 Time Step:     60, Simulation Time:      0.17 s
 Time Step:     70, Simulation Time:      0.17 s
 Time Step:     80, Simulation Time:      0.17 s
 Time Step:     90, Simulation Time:      0.18 s
 Time Step:    100, Simulation Time:      0.18 s
 Time Step:    200, Simulation Time:      0.23 s

STOP: Numerical Instability (CHID: 660_NETHF-52_w_HT3D_VENT)
```

This is intel db 

```
$ fds-int-db 660_NETHF-52_w_HT3D_VENT.fds 

 Fire Dynamics Simulator

 Current Date     : March  8, 2018  19:43:49
 Revision         : FDS6.6.0-1330-g5e5a047-dirty-master
 Revision Date    : Thu Mar 8 11:56:06 2018 -0500
 Compiler         : Intel ifort 17.0.3
 Compilation Date : Mar 08, 2018  19:28:49

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Enabled; Number of OpenMP Threads:      1

 MPI version: 3.1
 MPI library version: Open MPI v3.0.0, package: Open MPI salah@benkorichi Distribution, ident: 3.0.0, repo rev: v3.0.0, Sep 12, 2017

 Job TITLE        : Heat conduction example
 Job ID string    : 660_NETHF-52_w_HT3D_VENT

 Time Step:      1, Simulation Time:      0.01 s
 Time Step:      2, Simulation Time:      0.02 s
 Time Step:      3, Simulation Time:      0.03 s
 Time Step:      4, Simulation Time:      0.04 s
 Time Step:      5, Simulation Time:      0.05 s
forrtl: severe (408): fort: (3): Subscript #1 of the array D_Z has value -17 which is less than the lower bound of 0

Image              PC                Routine            Line        Source             
fds_mpi_intel_lin  00000000090302D6  Unknown               Unknown  Unknown
fds_mpi_intel_lin  0000000002E9A041  wall_routinesdiff        1402  wall.f90
fds_mpi_intel_lin  0000000002E98063  wall_routines_mp_        1371  wall.f90
fds_mpi_intel_lin  0000000002DCB44D  wall_routines_mp_          52  wall.f90
fds_mpi_intel_lin  00000000035FC548  MAIN__                    685  main.f90
fds_mpi_intel_lin  000000000040CDAE  Unknown               Unknown  Unknown
libc-2.23.so       0000146816665830  __libc_start_main     Unknown  Unknown
fds_mpi_intel_lin  000000000040CCA9  Unknown               Unknown  Unknown
```

gnu db 
```
$ fds-gnu-db 660_NETHF-52_w_HT3D_VENT.fds

 Fire Dynamics Simulator

 Current Date     : March  8, 2018  19:53:15
 Revision         : FDS6.6.0-1330-g5e5a047-dirty-master
 Revision Date    : Thu Mar 8 11:56:06 2018 -0500
 Compiler         : Gnu gfortran 7.2.0-1ubuntu1~16.04)
 Compilation Date : Mar 08, 2018  19:51:53

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Enabled; Number of OpenMP Threads:      1

 MPI version: 3.1
 MPI library version: Open MPI v3.0.0, package: Open MPI salah@sbenkorichi Distribution, ident: 3.0.0, repo rev: v3.0.0, Sep 12, 2017

 Job TITLE        : Heat conduction example
 Job ID string    : 660_NETHF-52_w_HT3D_VENT

 Time Step:      1, Simulation Time:      0.01 s
 Time Step:      2, Simulation Time:      0.02 s
 Time Step:      3, Simulation Time:      0.03 s
 Time Step:      4, Simulation Time:      0.04 s
 Time Step:      5, Simulation Time:      0.05 s
At line 1402 of file ../../Source/wall.f90
Fortran runtime error: Index '-16' of dimension 1 of array 'd_z' below lower bound of 0

Error termination. Backtrace:
#0  0x14e85ca90fba in ???
#1  0x14e85ca91ba5 in ???
#2  0x14e85ca91f77 in ???
#3  0x12667e6 in calculate_rho_d_f
	at ../../Source/wall.f90:1402
#4  0x1266a68 in diffusivity_bc
	at ../../Source/wall.f90:1371
#5  0x129de0c in __wall_routines_MOD_wall_bc
	at ../../Source/wall.f90:52
#6  0x14b03df in fds
	at ../../Source/main.f90:685
#7  0x15320b2 in main

```

[660_NETHF-52_w_HT3D_VENT.fds.txt](https://github.com/firemodels/fds/files/1794568/660_NETHF-52_w_HT3D_VENT.fds.txt)

Unless, the user is doing something isn't right. I will also check the input file.

**Comment by rmcdermo** [comment]
The set up is not right.  But it's not the user's fault.  I am still trying to get the guidance right in the user guide and it is not there yet.

There are a couple problems:

1. Please clean up the input files before posting them.  I already said not to have lots of 1D parameters and extra SURF lines.  It is really hard when I have to triple check every character of an input file to see where the error might be.  Salah, I expect you to help with this if you are posting issues.

2. NET_HEAT_FLUX is not a good bc to use for coupled HT3D problems.  If you add HT3D to the SURF line with latest code it throws an error if a flux bc is specified.  And if you are not doing 2-way coupling, think about what you are asking the code: it knows nothing about the flow field or radiation field yet.  All it has is a gas phase temperature and a face temperature of ambient.  Then you tell it to apply a NET HEAT FLUX of 52 kW/m2 into the solid.  What does that mean?  Given the fixed gas phase temperature TMP_G=TMPA, the cell face temperature has to become negative to achieve convective heat transfer in that direction.  There is nothing physically correct about this.  The correct way to deal with it is to use EXTERNAL_FLUX with HT3D=T on the SURF line (this actually is in the user guide).  That is set up in the attached input file.

[660_EF52_w_HT3D_VENT.fds.txt](https://github.com/firemodels/fds/files/1795010/660_EF52_w_HT3D_VENT.fds.txt)
